### ISSUE TITLE
Slider Tracker goes out of range

### ISSUE THREAD

**Issue by tuke307** [contrix09/XF-Material-Library#323]
#201 
 🐛 Bug Report

The XF-MaterialSlider is buggy with some small Min and Max Values set. 

### Expected behavior
The Tracker goes out of range and I can't see him anymore. With some really small Values (eg. Min=6, Max=12) the tracker goes instantly out of range every time i click it. the normal Xamarin Forms slider works fine with all values.

### Reproduction steps
not working:
```
<material:MaterialSlider MaxValue="12"
                                        MinValue="6">
</material:MaterialSlider>
```

working:
```
<Slider Maximum="12"
            Minimum="6">
</Slider>
```

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

![Screenshot (13)_LI](https://user-images.githubusercontent.com/58882912/79076770-ff985e80-7cfc-11ea-8d5f-a0441a6ec4d2.jpg)
